name:                crypto-ledger
version:             0.1.0.0
github:              "VlachJosef/crypto-ledger"
license:             BSD3
author:              "Josef Vlach"
maintainer:          "evlach.josef@gmail.com"
copyright:           "2018 Josef Vlach"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/crypto-ledger#readme>
default-extensions:
- OverloadedStrings
dependencies:
- base >= 4.7 && < 5
- ed25519
- bytestring
- serokell-test-task-lib ^>= 1.0
- network
- optparse-applicative
- binary
- base58-bytestring
- SHA
- containers
- bytestring-conversion
- newtype-generics
- time
- directory
- boxes

library:
  source-dirs: src

executables:
  crypto-ledger-node:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-ledger

  crypto-ledger-client:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-ledger

tests:
  crypto-ledger-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-ledger
    - hspec
